# Generated by Django 4.0.8 on 2023-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
