# Generated by Django 4.0.8 on 2023-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_profile_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(blank=True, help_text='An artistry name. This is your public name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='An impressive biography.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Tell the world where you are from.', max_length=30),
        ),
    ]
