# Generated by Django 4.0.8 on 2023-03-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_remove_followrequest_followed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, 'Solid'), (1, 'Syrup'), (2, 'Carbonated'), (3, 'Still')])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_alcohol', models.BooleanField(help_text='Does this ingredient contain any alcohol?')),
                ('alcohol_percentage', models.FloatField(help_text='Should be between 0 and 100')),
                ('density', models.FloatField(default=1000, help_text='In grams per liter [g/L]')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(blank=True, help_text='An artistry name. This is your public name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Tell the world where you are from.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
